"""9.30_1

Revision ID: bcd130d74796
Revises: 21cba3bd9325
Create Date: 2019-09-30 16:07:05.042043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcd130d74796'
down_revision = '21cba3bd9325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'author', ['name'])
    op.drop_column('author', 'age')
    op.drop_column('author', 'gender')
    op.drop_index('books_ibfk_1', table_name='books')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('books_ibfk_1', 'books', ['author_id'], unique=False)
    op.add_column('author', sa.Column('gender', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('author', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'author', type_='unique')
    # ### end Alembic commands ###
