"""9.30_2

Revision ID: e8354dd6f574
Revises: bcd130d74796
Create Date: 2019-09-30 16:08:01.491199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8354dd6f574'
down_revision = 'bcd130d74796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('author', sa.Column('gender', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'gender')
    op.drop_column('author', 'age')
    # ### end Alembic commands ###
